package:
  name: markupsafe
  version: !!str 0.18

source:
  fn: MarkupSafe-0.18.tar.gz
  url: https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.18.tar.gz
  md5: f8d252fd05371e51dec2fe9a36890687

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - markupsafe

about:
  home: http://github.com/mitsuhiko/markupsafe
  license: BSD License

